[package]
name = "comet"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["multipart", "ws"] }
sqlx = { version = "0.9.0", features = ["sqlite", "runtime-tokio"] }
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
jsonwebtoken = { version = "10", features = ["aws_lc_rs"] }
serde = {version = "1.0", features = ["derive"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
argon2 = "0.5.3"
rand = "0.8.5"
tower-http = { version = "0.7.0", features = ["cors"] }
nanoid = "0.5.0"
hex = "0.4.3"
sha2 = "0.11.0"
tokio-util = { version = "0.7.18", features = ["io"] }
serde_json = "1.0.150"
futures-util = "0.3.33"
kamadak-exif = "0.6.1"
lofty = "0.24.0"
