# The interface the app is going to run on. Leave it as If
# you don't know what you're doing.
bind_addr = [0, 0, 0, 0]

# The port the app is going to run on.
bind_port = 3000

# Password for authorized endpoints. Such as the upload endpoint.
# would recommend generating a random password with `openssl rand -base64 48`
# which should be strong enough.
password = "hiii"

# The length of the randomly generated file names.
# The higher the number, the lesser chance of colision probability.
file_name_length = 8

# Where the file goes on disk, just leave it as it is. Must end with a
# [forward] slash (/).
file_save_path = "media/"

# This config is used to set a limit to the files being uploaded, the value takes in bytes.
# So, a simple equation to get 5MB is (5 * 1024 * 1024), by default this config is 50MB. If
# the value passed in is ``0``, the limit would be disabled.
file_size_limit = 0

# Should the serve endpoint require an extension along with the file UID.
# for instance, the get route would be `/YbdlPsdg.png` instead of `/YbdlPsdg`
# enabling this would make the get route more explicit.
enforce_file_extensions = true

# If the uploaded file has no content_type, this content_type would be used.
# Its fine for most cases, so just leaving it as is is fine.
fallback_content_type = "application/octet-stream"


# The path for each endpoint can be specifiec below, leaving it as is is fine.
[endpoints]
get_file = "/media/" # Endpoint for serving files, Must end with (forward) slash [/].
delete_file = "/delete/" # Endpoint for deleting files, Must end with (forward) slash [/].
upload_file = "/upload" # Endpoint for uploading files.
ping = "/ping"
