services:
  backend:
    build:
      dockerfile: backend.Dockerfile
    restart: unless-stopped
    volumes:
      - './uploads:/data/uploads'

  app:
    build:
      dockerfile: frontend.Dockerfile
      args:
        - APP_API_URL=/api
        - APP_WS_URL=/api
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3001:80"
